### PR TITLE
New website

### PR DESCRIPTION
**Pull request by TParcollet**
Here it is ...

[x] First template version
[x] Update the text
[x] Link to all tutorials.

### CODE REVIEW

**Comment by lorenlugosch** [comment]
@TParcollet should that `cd` go in the main repo README as well?

**Comment by TParcollet** [comment]
Yes @lorenlugosch .. :p

**Comment by lorenlugosch** [comment]
Aight, 'tis done (directly on Github, have mercy on me!)

**Comment by lorenlugosch** [comment]
@TParcollet did you get rid of that comment Nauman mentioned ("if you don't like the library, go make your own" or something like that)? I would do it myself, but I don't remember where it is in the website

**Comment by TParcollet** [comment]
Yes, it is online. This PR isn't up to date anymore ..

**Comment by TParcollet** [comment]
@lorenlugosch The website is updated again, if you want to have a final look :)

**Comment by lorenlugosch** [comment]
@TParcollet looks good to me!

**Pull request merged**
